/*
 * This source file was generated by the Gradle 'init' task
 */
package _002_HelloWorld;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FirstProgramTester {
    @Test void testFixError() {
    	
        
    	String error = "no error";
        try {
        	FirstProgram.main(null);
        }catch(Exception e) {
        	error = e.toString();       
        }
        assertTrue(error == "no error");
    }
}
