/*
 * This source file was generated by the Gradle 'init' task
 */
package _002_HelloWorld;

public class FirstProgram {
    public static void main(String[] args) {
    	System.out.print("There are 3 erros \n")
    	System.OUT.println("once you find and fix them");
    	System.out.println(Then write me a story about your favorite hobby)
    }
}
