/*
 * This source file was generated by the Gradle 'init' task
 */
package _002_HelloWorld;

public class FirstProgram {
    public static void main(String[] args) {
    	System.out.print("Hello World");
    }
}
